### ISSUE TITLE
Error in wmake

### ISSUE THREAD

**Issue by SuperMaxusa** [jhhoward/MicroWeb#10]
Hello, I decided to try compile MicroWeb in DOSBox 0.74-3, but i getting this error:
![mw](https://user-images.githubusercontent.com/41739128/137544685-1381eeca-1a2f-4bbf-904f-8546797bbbeb.png)

How I can fix this error?
OpenWatcom 1.9, target: DOS

Thanks for this project :)

**Comment by SuperMaxusa** [comment]
Windows 10:
![w](https://user-images.githubusercontent.com/41739128/137580434-bbbf5be7-89cf-4590-9686-bf99b3f8eeb5.png)

**Comment by jhhoward** [comment]
I haven't tried compiling in DOS so unsure why it is failing there.

For Windows, it looks like you don't have all of your environment variables configured for Watcom (as it is failing to include standard C header files)

If you look in the build.bat script, it sets the environment variables needed for compilation (assuming Watcom is installed at C:\WATCOM)

For reference these are the variables that are set:
set PATH=c:\watcom\binnt;%PATH%
set INCLUDE=c:\watcom\h
set WATCOM=c:\watcom
set EDPATH=c:\watcom\eddat
set WIPFC=c:\watcom\wipfc
set LIBDOS=c:\watcom\lib286\dos;c:\watcom\lib286

I believe the INCLUDE path is missing from your setup as this is where the compiler will need to look to find stdio.h, stlib.h, stdint.h etc

**Comment by SuperMaxusa** [comment]
I noticed that wpp.exe is installed only in the version for MS-DOS. Maybe because of this the problem?
![wpp](https://user-images.githubusercontent.com/41739128/137619249-749bf3a8-55bc-4cea-9146-48c240fcef6e.png)

**Comment by jhhoward** [comment]
The binaries in the WATCOM\binw directory are the DOS versions. You will need to use the binaries in WATCOM\binnt if you are compiling in Windows. Compiling in DOS is currently not supported for various reasons.
