### ISSUE TITLE
200LX Visibility Issues

### ISSUE THREAD

**Issue by jakfish** [jhhoward/MicroWeb#15]
This is an extraordinary program -- thank you for all your hard work. Running MicroWeb -c on Omnibook 425 makes for easy reading, but MicroWeb on the 200LX is very hard on the eyes, and the MWEB95.EXE only partially fills the 200LX screen.

Would it be difficult to allow a choice of font size and an option for bold-ing?

Thanks again for making a browser that drags DOS kicking and screaming into 2022.

**Comment by jhhoward** [comment]
Version 2.0 now includes a palmtop video mode option which uses a more appropriate sized font for HP palmtops
