### ISSUE TITLE
Microweb is trying to fetch anchor links "#" as entirely new objects

### ISSUE THREAD

**Issue by mbbrutman** [jhhoward/MicroWeb#23]
A URL of the form http://server/path/object#anchor means "jump to anchor within object".  If object (a page) is already loaded then it's just a local jump to an anchor tag within the page.

Microweb is interpreting these types of links as entirely new pages to fetch, which is going to fail because the #anchor part is being passed along as the name of the object to fetch.   If a fetch is required then the #anchor part should be stripped out of the request to the server.  After the object is fetched the screen can then be scrolled to #anchor.

If you're not parsing the anchor links in the page then just stripping the #anchor before sending to the web server should be sufficient; the user should be able to figure out how to scroll by themselves.

**Comment by jhhoward** [comment]
This is now supported properly in version 2.0

**Comment by mbbrutman** [comment]
Thank you sir!
