### ISSUE TITLE
Something is wrong with relative url parsing (MW 0.53)

### ISSUE THREAD

**Issue by bocke** [jhhoward/MicroWeb#24]
I'm currently trying out the latest release of MW and I noticed it has some problem with parsing relative urls.

If I'm viewing document called **index.htm** which contains a relative link: 

```html
<a href="link1.htm">Link 1</a>
```
MW will parse the link as 

```
FILE://INDEX.HTM/LINK1.HTM
```

instead of:

```
FILE://LINK1.HTM
```

I can get MW to open the right document by using absolute urls: 

```html
<a href="file://link1.htm">Link 1</a>
```

I haven't yet looked into the code, so I don't know if this would be a simple fix or something more tedious (as it probably touches URL parsing code). 

**Edit:**

MW was only tested offline in a DOSBox-x session. MW and all the HTM files were in the root directory of the C: drive.

**Comment by jhhoward** [comment]
Fixed in version 2.0
