### ISSUE TITLE
Umlauts support

### ISSUE THREAD

**Issue by freakedenough** [jhhoward/MicroWeb#35]
I suggest to add support for German umlauts. Currently all HTML codes resembling them are rendered as raw text, making it hard to read texts in certain cases.

![20240719_231330](https://github.com/user-attachments/assets/b67289ec-72e1-4a04-9903-ca5f7d86dd31)

```
&uuml; for small ü
&Uuml; for big Ü
&auml; for small ä
&Auml; for big Ä
&ouml; for small ö
&Ouml; for big Ö
&szlig; for small sharp s: ß
&#7838; for big sharp s: ẞ
```

If you are not able to display umlauts natively, you can also display "ü" as "ue" (and so on and so forth) instead, which is still correct for German. Sharp S letters (ß and ẞ) can be replaced by "ss" and "SS." The uppercase sharp S is relatively new (so there is no `&Szlig;` as you would expect). If you can display the lowercase sharp S, you can also use it for the uppercase sharp S, and no one will be bothered. They look almost identical.

**Comment by Carmina16** [comment]
Currently it is impossible due to the weird logic of the parser.

**Comment by jhhoward** [comment]
I've made a change to add support for additional character entities to support umlauts. (see commit 1532472d3599c29cdb676d49c1ef21869a7d3a2c) 
It will be in the next release.

> &#7838; for big sharp s: ẞ

This isn't fixed yet as it references as this range is in a unicode code page I haven't implemented yet

**Comment by freakedenough** [comment]
Thank you very much! That is a great change with many more additional entities I didn't even think of initially.
I did rewrite my website zu use decimal entities, they worked and were correctly displayed. I noticed € is also one of these characters that can be displayed natively under DOS, so I fall back to "EUR" instead.
```
// HTML entities
"/#7838;/" => "#223;",
"/szlig;/" => "#223;",
"/Auml;/" => "#196;",
"/auml;/" => "#228;",
"/Ouml;/" => "#214;",
"/ouml;/" => "#246;",
"/Uuml;/" => "#220;",
"/uuml;/" => "#252;",
"/&euro;/" => "EUR",
```
