### ISSUE TITLE
More packet drivers in boot disk

### ISSUE THREAD

**Issue by roytam1** [jhhoward/MicroWeb#5]
I think it is good to provide more packet drivers (for example, AMD PCNet driver for pcnet/vlance, rtl8029as (ne2k_pci), rtl8139) so people can test microweb on more VMs.

**Comment by roytam1** [comment]
modified config.sys/autoexec.bat and additional drivers attached.
[packet-drivers.zip](https://github.com/jhhoward/MicroWeb/files/6871643/packet-drivers.zip)

**Comment by roytam1** [comment]
and you can use Dave Dunfield's DHCP.COM to save more space in 360K disk image:
http://dunfield.classiccmp.org/dos/index.htm

**Comment by jhhoward** [comment]
Thanks I will take a look at the drivers you suggested! The 360K disk may be a bit of a squeeze depending on how big the drivers are

**Comment by jhhoward** [comment]
I added the packet drivers you suggested plus a few more that are supported by 86box. There is also now a modded version of the NE2000 driver that should work on XT machines
