### ISSUE TITLE
Crashes on startup - IBM 5162 (286)

### ISSUE THREAD

**Issue by ajrossnz** [jhhoward/MicroWeb#7]
I have an IBM 5162 with DOS 6.22 and an ATI All in wonder EGA+ card. 3com 3c509. The binary crashes on run, doesn't switch to graphics mode, just hangs. Any clues? Would love to check this out!

**Comment by jhhoward** [comment]
Are you using prebuilt binaries or building from source?

Some things you can try:
* Run with the -c command line option to use 640x200 CGA mode
* Trying running without the packet driver loaded (in case the packet driver is the problem)

**Comment by ajrossnz** [comment]
Thanks, I think it was identifying the card incorrectly. I have an ATI EGA Wonder 800+ for your information.
Starting with either -e or -c works just fine, thank you for your help!
